### ISSUE TITLE
API Update

### ISSUE THREAD

**Issue by bencleary** [bencleary/django-timescaledb#3]
Working with the package for the last year and a half now has opened up some areas where improvement is needed and required. This will be a breaking change but will allow for a more stable platform to build from.

### Tasks

- [x] Add pylint, black and other formatting tools
- [x] Remove the models.models. import string, and tidy up imports
- [x] Move the TimescaleModel to a utils package instead, it doesn't need to be the primary use as indicated by the multiple "why does 'time' need to be used statements"
- [x] Update queryset methods to reflect the lastest implementation from TimescaleDB
- [x] Add unit tests various parts
- [x] Add integration tests using the example project
- [ ] Update the example project to show a more real-life example
- [ ] Add documentation site 
- [ ] First pass of simple types

### Potential or Investigative

- [ ] Look at an admin integration interface
- [ ] Retention periods
- [ ] Compression
- [ ] Distributed Tables

**Comment by bencleary** [comment]
Need to identify a testing plan as to where the most useful tests can be placed. A large chunk of the code base is behavioural rather than functional, i.e it requires something else to work, like the time_bucket function can only be used as part of a query. An initial testing plan is below:

Unit

- Field properties
- Util model properties

Integration (i.e requires a model and data to test)

- Expressions
- Aggregates
- Manages
- Querysets

All testing will be done through PyTest and will have a simple Django application configured for Timescale. It will require a timescale database instance to test against, i.e docker.

**Comment by bencleary** [comment]
Added more tests and better exception handling within the database expressions. Test suite is still growing and will require review.

**Comment by bencleary** [comment]
Tests have been added and structure for tests has been decided:

- [ ] Test aggregate methods
- [x] Test expression methods
- [ ] Test full queries
- [x] Test field methods and properties

**Comment by bencleary** [comment]
@schlunsen - are you able to review anything that is currently in progress, in-particular the test suites to see if i have missed anything obvious so far?

**Comment by bencleary** [comment]
During current work the following tasks needs to be completed:

- [ ] reduce duplicated logic in within expressions (checks for types, and formats, investigate using partials)
- [ ] TimeBucketGapFill test suite feels pretty flaky, add more edge cases and failing test suites
- [ ] Finish documentation for TimescaleModel - explain field names, and reasoning
- [ ] Add logging interface
- [ ] Mark Last & First as depreciated in this package
- [ ] Initial types for querysets and managers (both inputs and outputs)
- [ ] Expand docs for querysets and managers
- [ ] Add check for manager and quersets to confirm model has a hypertable to use
